sudo: false
language: node_js
node_js:
- stable
- '4.2'
- '0.12'
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_b1bff780d79a_key -iv $encrypted_b1bff780d79a_iv
  -in config.js.enc -out config.js -d
- openssl aes-256-cbc -K $encrypted_b1bff780d79a_key -iv $encrypted_b1bff780d79a_iv
  -in node-gcm-for-ws-940512693898.json.enc -out node-gcm-for-ws-940512693898.json
  -d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: node-gcm-for-ws-940512693898.json
  default: true
  project: node-gcm-for-ws
  version: 20151120t153600
