sudo: false
language: node_js
node_js:
- stable
- '4.2'
before_install:
- openssl aes-256-cbc -K $encrypted_b1bff780d79a_key -iv $encrypted_b1bff780d79a_iv
  -in secure.files.tar.enc -out secure.files.tar -d
- tar -xvf secure.files.tar
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: node-gcm-for-ws-940512693898.json
  default: true
  project: node-gcm-for-ws
  version: 20151120t153600
